services:
  app:
    restart: always
    build:
      context: .
    environment:
      VIRTUAL_HOST: "timetable.alxr.uk"
    expose:
      - "3000"
    networks:
      - rev-proxy-net

networks:
  rev-proxy-net:
    external: true
